merge everything in one parallelisation

diff --git a/.github/workflows/gendocs.yaml b/.github/workflows/gendocs.yaml
--- a/.github/workflows/gendocs.yaml
+++ b/.github/workflows/gendocs.yaml
@@ -48,43 +48,37 @@ jobs:
           fetch-depth: 1
           token: ${{ secrets.BOT_TOKEN }}
           
-      - name: Helm Dependency Fetch
+      - name: Security Scan
         shell: bash
         run: |
           helm_dep() {
               helm dependency update "${1}" --skip-refresh || (sleep 10 && helm dependency update "${1}" --skip-refresh) || (sleep 10 && helm dependency update "${1}" --skip-refresh)
               }
           export -f helm_dep
-          for chart in charts/charts/**/* ; do
-            helm_dep ${chart} &
-          done
-          wait
-      - name: Helm Security Scan
-        shell: bash
-        run: |
-          helm_sec_scan() {
+          
+          scan_prep() {
               local chart="$1"
               local chartname="$(basename ${chart})"
               local train="$(basename $(dirname "${chart}"))"
-              echo "Scanning helm security for ${chartname}"
+              echo "Preparing security scans for: ${chartname}"
               mkdir -p ${chart}/render
               rm -rf docs/charts/${train}/${chartname}/security.md || echo "removing old security.md file failed..."
               cat charts/templates/security.tpl >> docs/charts/${train}/${chartname}/security.md
               echo "" >> docs/charts/${train}/${chartname}/security.md
-              helm template ${chart} --output-dir ${chart}/render > /dev/null
+              helm template ${chart} --output-dir ${chart}/render > /dev/null || (  echo "helm templating failed..." && return 0 )
+              }
+           export -f scan_prep
+           
+          helm_sec_scan() {
+              local chart="$1"
+              local chartname="$(basename ${chart})"
+              local train="$(basename $(dirname "${chart}"))"
               trivy config -f template --template "@./charts/templates/trivy-config.tpl" -o ${chart}/render/tmpsec${chartname}.md ${chart}/render
               rm -rf ${chart}/render/tmpsec${chartname}.md || true
               echo "" >> docs/charts/${train}/${chartname}/security.md
               }
            export -f helm_sec_scan
-           for chart in charts/charts/**/* ; do
-             helm_sec_scan "$chart" &
-           done
-           wait
            
-      - name: Container Security Scan
-        shell: bash
-        run: |
           container_sec_scan() {
               local chart="$1"
               local chartname="$(basename ${chart})"
@@ -109,10 +103,21 @@ jobs:
               done
               }
            export -f container_sec_scan
-           for chart in charts/charts/**/* ; do
-             container_sec_scan "$chart" &
-           done
-           wait
+           
+          run_scans() {
+              local chart="$1"
+              local chartname="$(basename ${chart})"
+              helm_dep ${chart}
+              scan_prep ${chart}
+              helm_sec_scan ${chart}
+              container_sec_scan ${chart}
+              }
+           export -f run_scans
+           
+          for chart in charts/charts/**/* ; do
+            run_scans ${chart} &
+          done
+          wait
            
       - name: Create commit
         uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
